"""add user model and user_id to invoices

Revision ID: 3f9fd07f1c2c
Revises: 
Create Date: 2026-05-20 08:39:11.815964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f9fd07f1c2c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tax_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('country', sa.String(length=5), nullable=False),
    sa.Column('gpm_percent', sa.Float(), nullable=True),
    sa.Column('expense_deduction_percent', sa.Float(), nullable=True),
    sa.Column('vsd_percent', sa.Float(), nullable=True),
    sa.Column('psd_percent', sa.Float(), nullable=True),
    sa.Column('is_custom', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('account_type', sa.String(length=20), nullable=False),
    sa.Column('activity_type', sa.String(length=20), nullable=False),
    sa.Column('country_code', sa.String(length=5), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_name', sa.String(length=200), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('date', sa.String(length=20), nullable=False),
    sa.Column('tax_paid', sa.Float(), nullable=False),
    sa.Column('expense_deduction_percent', sa.Float(), nullable=True),
    sa.Column('vsd_percent', sa.Float(), nullable=True),
    sa.Column('psd_percent', sa.Float(), nullable=True),
    sa.Column('net_income', sa.Float(), nullable=True),
    sa.Column('gpm', sa.Float(), nullable=True),
    sa.Column('vsd', sa.Float(), nullable=True),
    sa.Column('psd', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invoices')
    op.drop_table('user')
    op.drop_table('tax_settings')
    # ### end Alembic commands ###
